# 服务端口
server:
  port: 8081
spring:
  application:
    name: baima
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:xxxx/baima?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: xxx
    password: xxx
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:**/xml/*.xml
  type-enums-package: com.gcu.baima.Enum

#自定义配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: xxx
      keysecret: xxxx
      bucketname: edu-guli-2023-04
